version: "3.1"

networks:
  public:
  private:

services:
  web:
    build: client
    command: npm start
    volumes:
      - .:/web
    networks:
      - public
      - private
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: .
    command: bundle exec rails s -b 0.0.0.0 -p 3001
    volumes:
      - .:/app
    networks:
      - public
      - private
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://gaming_base:gaming_base@postgres/gaming_base_dev
      REDIS_URL: redis://redis

  sidekiq:
    build: .
    command: bundle exec sidekiq -q default -q mailers
    volumes:
      - .:/app
    networks:
      - private
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://gaming_base:gaming_base@postgres/gaming_base_dev
      REDIS_URL: redis://redis

  postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'gaming_base'
      POSTGRES_PASSWORD: 'gaming_base'
      POSTGRES_DB: 'gaming_base_dev'
    networks:
      - private
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis'
    sysctls:
      - "net.core.somaxconn=1024"
    command: redis-server --appendonly yes
    networks:
      - private
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

volumes:
  redis:
  postgres:
