version: "3"

services:
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://gaming_base@postgres/gaming_base_dev

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'gaming_base'
      POSTGRES_DB: 'gaming_base_dev'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass gaming_base
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

volumes:
  redis:
  postgres:
